[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = CO
ST = Cundinamarca
L = Bogota
O = Unisabana
CN = cliente

[v3_req]
subjectAltName = DNS:localhost, DNS:127.0.0.1, IP:127.0.0.1
